use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

#[derive(Debug, Serialize, Deserialize)]
pub struct BuildResult {
    pub success: bool,
    pub output_path: String,
    pub stdout: String,
    pub stderr: String,
}

/// Detect whether a folder is an mdbook project (has book.toml) or raw markdown.
#[tauri::command]
pub async fn detect_project_type_mdbook(folder_path: String) -> Result<String, String> {
    let path = PathBuf::from(&folder_path);
    if path.join("book.toml").exists() {
        Ok("project".to_string())
    } else if has_markdown_files(&path) {
        Ok("markdown".to_string())
    } else {
        Ok("empty".to_string())
    }
}

/// Convert a raw markdown folder into an mdbook project structure.
/// Creates src/, dist/ (output), assets/, README.md for GitHub Pages hosting.
#[tauri::command]
pub async fn convert_to_project_mdbook(folder_path: String, title: String) -> Result<(), String> {
    let root = PathBuf::from(&folder_path);
    let src_dir = root.join("src");
    let assets_dir = root.join("assets");
    let dist_dir = root.join("dist");

    // Create required directories
    std::fs::create_dir_all(&src_dir).map_err(|e| e.to_string())?;
    std::fs::create_dir_all(&assets_dir).map_err(|e| e.to_string())?;
    std::fs::create_dir_all(&dist_dir).map_err(|e| e.to_string())?;

    // Move all .md files into src/
    move_markdown_content(&root, &src_dir)?;

    // Create PROJECT README.md for GitHub Pages after moving source markdown so it stays at repo root.
    let readme_content = format!(
        r#"# {title}

This is an [mdBook](https://rust-lang.github.io/mdBook/) project hosted on [GitHub Pages](https://pages.github.com/).

## Project Structure

- **src/** — Markdown documentation files
- **dist/** — Built HTML output (generated by mdBook)
- **assets/** — Images and static files
- **book.toml** — mdBook configuration

## Building

Install mdBook:
```bash
cargo install mdbook
```

Build the site:
```bash
mdbook build
```

Preview locally:
```bash
mdbook serve
```

## Deployment

The `dist/` folder is ready to deploy to GitHub Pages. Configure your repository settings to serve from the `dist/` directory.
"#
    );
    std::fs::write(root.join("README.md"), readme_content).map_err(|e| e.to_string())?;

    ensure_index_md(&src_dir)?;
    ensure_summary_md(&src_dir)?;

    // Write book.toml
    let book_toml = format!(
        r#"[book]
title = "{title}"
authors = []
language = "en"
description = "{title}"

[build]
build-dir = "dist"

[output.html]
"#
    );
    std::fs::write(root.join("book.toml"), book_toml).map_err(|e| e.to_string())?;

    Ok(())
}

/// Build the mdbook site from project or markdown sources.
#[tauri::command]
pub async fn build_site_mdbook(
    source_folder: String,
    output_folder: String,
) -> Result<BuildResult, String> {
    let source = PathBuf::from(&source_folder);
    let output = PathBuf::from(&output_folder);

    if !source.exists() {
        return Err("Source folder does not exist".to_string());
    }

    clean_output_dir(&output)?;

    let is_project = source.join("book.toml").exists();

    if is_project {
        build_mdbook_project(&source, &output).await
    } else {
        build_from_raw_markdown(&source, &output).await
    }
}

#[tauri::command]
pub async fn preview_site_mdbook(source_folder: String) -> Result<BuildResult, String> {
    let temp_output = std::env::temp_dir().join("frontdocs_preview_mdbook");
    build_site_mdbook(
        source_folder,
        temp_output.to_string_lossy().to_string(),
    )
    .await
}

/// Build from an existing mdbook project (has book.toml + src/)
async fn build_mdbook_project(
    project_dir: &PathBuf,
    output_dir: &PathBuf,
) -> Result<BuildResult, String> {
    // Patch book.toml to set build-dir
    let original_toml = std::fs::read_to_string(project_dir.join("book.toml"))
        .map_err(|e| e.to_string())?;

    // Copy project to temp dir so we can patch without modifying original
    let build_dir = std::env::temp_dir().join("frontdocs_mdbook_build");
    if build_dir.exists() {
        std::fs::remove_dir_all(&build_dir).map_err(|e| e.to_string())?;
    }
    copy_dir_recursive(project_dir, &build_dir)?;

    let docs_dir = build_dir.join("src");
    if docs_dir.exists() {
        preprocess_wiki_links_in_dir(&docs_dir)?;
    }

    // Patch book.toml to set build-dir to the desired output
    let output_str = normalize_path(&output_dir.to_string_lossy());
    let mut toml_lines = Vec::new();
    let mut in_build_section = false;
    let mut saw_build_section = false;

    for line in original_toml.lines() {
        if line.contains("[build]") {
            toml_lines.push("[build]".to_string());
            toml_lines.push(format!(r#"build-dir = "{}""#, output_str));
            in_build_section = true;
            saw_build_section = true;
        } else if in_build_section && line.starts_with("[") {
            // End of [build] section
            toml_lines.push(line.to_string());
            in_build_section = false;
        } else if !in_build_section || !line.contains("build-dir") {
            toml_lines.push(line.to_string());
        }
    }

    if !saw_build_section {
        toml_lines.push(format!("\n[build]\nbuild-dir = \"{}\"", output_str));
    }

    std::fs::write(build_dir.join("book.toml"), toml_lines.join("\n"))
        .map_err(|e| e.to_string())?;

    let result = run_mdbook(&build_dir).await?;

    // Clean up temp build dir
    let _ = std::fs::remove_dir_all(&build_dir);

    Ok(result)
}

/// Build from a raw markdown folder (no book.toml)
async fn build_from_raw_markdown(
    source: &PathBuf,
    output_dir: &PathBuf,
) -> Result<BuildResult, String> {
    let build_dir = std::env::temp_dir().join("frontdocs_mdbook_build");
    if build_dir.exists() {
        std::fs::remove_dir_all(&build_dir).map_err(|e| e.to_string())?;
    }
    std::fs::create_dir_all(&build_dir).map_err(|e| e.to_string())?;

    // Determine title from folder name
    let title = source
        .file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .to_string();
    let title = capitalize_words(&title.replace('-', " ").replace('_', " "));

    // Copy markdown content into src/
    let src_dir = build_dir.join("src");
    std::fs::create_dir_all(&src_dir).map_err(|e| e.to_string())?;
    copy_markdown_content(source, &src_dir)?;

    ensure_index_md(&src_dir)?;
    ensure_summary_md(&src_dir)?;

    let output_str = normalize_path(&output_dir.to_string_lossy());

    // Write book.toml
    let book_toml = format!(
        r#"[book]
title = "{title}"
authors = []
language = "en"
description = "{title}"

[build]
build-dir = "{output_str}"

[output.html]
"#
    );
    std::fs::write(build_dir.join("book.toml"), book_toml).map_err(|e| e.to_string())?;

    let result = run_mdbook(&build_dir).await?;

    // Clean up
    let _ = std::fs::remove_dir_all(&build_dir);

    Ok(result)
}

// ── Helpers ─────────────────────────────────────────────────────────────────

fn has_markdown_files(dir: &Path) -> bool {
    WalkDir::new(dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .any(|e| {
            e.file_type().is_file()
                && e.path()
                    .extension()
                    .map_or(false, |ext| ext == "md" || ext == "markdown")
        })
}

fn normalize_path(p: &str) -> String {
    p.replace('\\', "/")
}

fn clean_output_dir(path: &Path) -> Result<(), String> {
    if path.exists() {
        std::fs::remove_dir_all(path).map_err(|e| e.to_string())?;
    }
    Ok(())
}

fn capitalize_words(s: &str) -> String {
    s.split_whitespace()
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + c.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn move_markdown_content(root: &Path, src_dir: &Path) -> Result<(), String> {
    for entry in std::fs::read_dir(root)
        .map_err(|e| e.to_string())?
        .filter_map(|e| e.ok())
    {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();

        // Skip special dirs/files
        if name == "src"
            || name == "dist"
            || name == "assets"
            || name == "book.toml"
            || name.starts_with('.')
        {
            continue;
        }

        if path.is_dir() {
            if has_markdown_files(&path) {
                let dest = src_dir.join(&name);
                std::fs::rename(&path, &dest).map_err(|e| {
                    if let Err(copy_err) = copy_dir_recursive(&path, &dest) {
                        return format!("Move failed: {} (copy fallback: {})", e, copy_err);
                    }
                    if let Err(rm_err) = std::fs::remove_dir_all(&path) {
                        return format!("Move partial — delete failed: {}", rm_err);
                    }
                    String::new()
                })
                .or_else(|e| if e.is_empty() { Ok(()) } else { Err(e) })?;
            }
        } else if path
            .extension()
            .map_or(false, |ext| ext == "md" || ext == "markdown")
        {
            let dest = src_dir.join(&name);
            std::fs::rename(&path, &dest).map_err(|e| e.to_string())?;
        }
    }
    Ok(())
}

fn copy_markdown_content(source: &Path, dest: &Path) -> Result<(), String> {
    let available_files = collect_markdown_files(source)?;

    for entry in WalkDir::new(source)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        let relative = entry.path().strip_prefix(source).unwrap_or(entry.path());

        if entry.file_type().is_dir() {
            std::fs::create_dir_all(dest.join(relative)).map_err(|e| e.to_string())?;
        } else if entry
            .path()
            .extension()
            .map_or(false, |ext| ext == "md" || ext == "markdown")
        {
            let content = std::fs::read_to_string(entry.path()).map_err(|e| e.to_string())?;
            let body = strip_frontmatter(&content).trim_start().to_string();
            let current_file = relative.to_string_lossy().replace('\\', "/");
            let body = convert_wiki_links(&body, &current_file, &available_files);
            let dest_file = dest.join(relative);
            if let Some(parent) = dest_file.parent() {
                std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
            }
            std::fs::write(&dest_file, body).map_err(|e| e.to_string())?;
        } else if entry.path().extension().map_or(false, |ext| {
            ext == "png"
                || ext == "jpg"
                || ext == "jpeg"
                || ext == "gif"
                || ext == "svg"
                || ext == "webp"
        }) {
            let dest_file = dest.join(relative);
            if let Some(parent) = dest_file.parent() {
                std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
            }
            std::fs::copy(entry.path(), &dest_file).map_err(|e| e.to_string())?;
        }
    }
    Ok(())
}

fn copy_dir_recursive(src: &Path, dst: &Path) -> Result<(), String> {
    std::fs::create_dir_all(dst).map_err(|e| e.to_string())?;
    for entry in std::fs::read_dir(src)
        .map_err(|e| e.to_string())?
        .filter_map(|e| e.ok())
    {
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            std::fs::copy(&src_path, &dst_path).map_err(|e| e.to_string())?;
        }
    }
    Ok(())
}

fn preprocess_wiki_links_in_dir(dir: &Path) -> Result<(), String> {
    let available_files = collect_markdown_files(dir)?;

    for entry in WalkDir::new(dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
    {
        if entry.path().extension().map_or(false, |ext| ext == "md" || ext == "markdown") {
            let content = std::fs::read_to_string(entry.path()).map_err(|e| e.to_string())?;
            let current_file = entry
                .path()
                .strip_prefix(dir)
                .unwrap_or(entry.path())
                .to_string_lossy()
                .replace('\\', "/");
            let converted = convert_wiki_links(&content, &current_file, &available_files);
            std::fs::write(entry.path(), converted).map_err(|e| e.to_string())?;
        }
    }

    Ok(())
}

fn collect_markdown_files(root: &Path) -> Result<Vec<String>, String> {
    let mut files = Vec::new();

    for entry in WalkDir::new(root)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
    {
        if entry.path().extension().map_or(false, |ext| ext == "md" || ext == "markdown") {
            let relative = entry
                .path()
                .strip_prefix(root)
                .unwrap_or(entry.path())
                .to_string_lossy()
                .replace('\\', "/");
            files.push(relative);
        }
    }

    Ok(files)
}

fn convert_wiki_links(content: &str, current_file: &str, available_files: &[String]) -> String {
    let mut result = String::new();
    let mut chars = content.chars().peekable();

    while let Some(ch) = chars.next() {
        if ch == '[' && chars.peek() == Some(&'[') {
            chars.next();
            let mut link_content = String::new();
            let mut found_closing = false;

            while let Some(link_ch) = chars.next() {
                if link_ch == ']' && chars.peek() == Some(&']') {
                    chars.next();
                    found_closing = true;
                    break;
                }
                link_content.push(link_ch);
            }

            if found_closing && !link_content.trim().is_empty() {
                let mut parts = link_content.splitn(2, '|');
                let target = parts.next().unwrap_or("").trim();
                let alias = parts.next().map(str::trim).filter(|value| !value.is_empty());
                let label = alias.unwrap_or(target);
                let resolved = resolve_link(target, current_file, available_files);
                result.push_str(&format!("[{}]({})", label, resolved));
            } else {
                result.push('[');
                result.push('[');
                result.push_str(&link_content);
            }
        } else {
            result.push(ch);
        }
    }

    result
}

fn resolve_link(link: &str, current_file: &str, available_files: &[String]) -> String {
    let candidates = build_link_candidates(link, current_file);

    for candidate in candidates {
        let normalized_candidate = normalize_link_key(&candidate);
        if let Some(file) = available_files.iter().find(|file| {
            normalize_link_key(&strip_markdown_extension(file)) == normalized_candidate
        }) {
            return markdown_path_to_relative_html_href(file, current_file);
        }
    }

    let target_name = path_basename(&normalize_link_target(link));
    let current_dir = path_dirname(&strip_markdown_extension(current_file));
    let mut fallback_matches: Vec<&String> = available_files
        .iter()
        .filter(|file| normalize_link_key(&strip_markdown_extension(&path_basename(file))) == normalize_link_key(&target_name))
        .collect();

    fallback_matches.sort_by_key(|file| path_distance(&current_dir, file));

    if let Some(best_match) = fallback_matches.first() {
        return markdown_path_to_relative_html_href(best_match, current_file);
    }

    markdown_path_to_relative_html_href(&format!("{}.md", normalize_link_target(link)), current_file)
}

fn normalize_link_target(value: &str) -> String {
    let normalized = value
        .trim()
        .split(['#', '?'])
        .next()
        .unwrap_or("")
        .trim()
        .replace('\\', "/")
        .trim_start_matches("./")
        .to_string();

    normalized
        .trim_end_matches("/index.html")
        .trim_end_matches(".html")
        .trim_end_matches(".markdown")
        .trim_end_matches(".md")
        .to_string()
}

fn strip_markdown_extension(value: &str) -> String {
    value
        .trim_end_matches(".markdown")
        .trim_end_matches(".md")
        .to_string()
}

fn build_link_candidates(link: &str, current_file: &str) -> Vec<String> {
    let target = normalize_link_target(link);
    if target.is_empty() {
        return Vec::new();
    }

    let mut candidates = vec![target.clone()];
    let mut current_dir = path_dirname(&strip_markdown_extension(current_file));
    while !current_dir.is_empty() {
        candidates.push(format!("{}/{}", current_dir, target));
        current_dir = path_dirname(&current_dir);
    }
    candidates
}

fn markdown_path_to_html_path(path: &str) -> String {
    let clean = strip_markdown_extension(path).replace('\\', "/");
    if clean.is_empty() || clean == "index" {
        "index.html".to_string()
    } else if clean.ends_with("/index") {
        format!("{}.html", clean)
    } else {
        format!("{}/index.html", clean)
    }
}

fn markdown_path_to_html_href(path: &str) -> String {
    markdown_path_to_html_path(path).replace(' ', "%20")
}

fn markdown_path_to_relative_html_href(path: &str, current_file: &str) -> String {
    let target_html = markdown_path_to_html_path(path);
    let current_html = markdown_path_to_html_path(current_file);
    let current_dir = path_dirname(&current_html);

    let from_parts: Vec<&str> = current_dir
        .split('/')
        .filter(|part| !part.is_empty())
        .collect();
    let to_parts: Vec<&str> = target_html
        .split('/')
        .filter(|part| !part.is_empty())
        .collect();

    let mut shared = 0;
    while shared < from_parts.len()
        && shared < to_parts.len()
        && from_parts[shared] == to_parts[shared]
    {
        shared += 1;
    }

    let mut segments: Vec<&str> = Vec::new();
    for _ in 0..(from_parts.len() - shared) {
        segments.push("..");
    }
    for part in to_parts.iter().skip(shared) {
        segments.push(part);
    }

    if segments.is_empty() {
        "index.html".to_string()
    } else {
        segments.join("/").replace(' ', "%20")
    }
}

fn path_dirname(value: &str) -> String {
    match value.rsplit_once('/') {
        Some((parent, _)) => parent.to_string(),
        None => String::new(),
    }
}

fn path_basename(value: &str) -> String {
    value.rsplit('/').next().unwrap_or(value).to_string()
}

fn path_distance(current_dir: &str, file_path: &str) -> usize {
    let current_parts: Vec<&str> = current_dir.split('/').filter(|part| !part.is_empty()).collect();
    let file_dir = path_dirname(&strip_markdown_extension(file_path));
    let file_parts: Vec<&str> = file_dir.split('/').filter(|part| !part.is_empty()).collect();
    let mut shared = 0;
    while shared < current_parts.len()
        && shared < file_parts.len()
        && current_parts[shared] == file_parts[shared]
    {
        shared += 1;
    }
    (current_parts.len() - shared) + (file_parts.len() - shared)
}

fn normalize_link_key(value: &str) -> String {
    value
        .to_lowercase()
        .replace("%20", " ")
        .replace('_', " ")
        .replace('\\', "/")
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

fn ensure_directory_style_html_aliases(output_dir: &Path) -> Result<(), String> {
    for entry in WalkDir::new(output_dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
    {
        if !entry.path().extension().map_or(false, |ext| ext == "html") {
            continue;
        }

        let relative = entry
            .path()
            .strip_prefix(output_dir)
            .unwrap_or(entry.path())
            .to_string_lossy()
            .replace('\\', "/");

        if relative == "index.html" || relative.ends_with("/index.html") || relative == "404.html" || relative == "print.html" {
            continue;
        }

        let alias_relative = markdown_path_to_html_href(&relative);
        let alias_path = output_dir.join(alias_relative.replace('/', std::path::MAIN_SEPARATOR_STR));
        if alias_path.exists() {
            continue;
        }
        if let Some(parent) = alias_path.parent() {
            if parent.exists() && parent.is_file() {
                continue;
            }
            if let Err(err) = std::fs::create_dir_all(parent) {
                if err.kind() == std::io::ErrorKind::AlreadyExists {
                    continue;
                }
                return Err(err.to_string());
            }
        }
        if let Err(err) = std::fs::copy(entry.path(), alias_path) {
            if err.kind() != std::io::ErrorKind::AlreadyExists {
                return Err(err.to_string());
            }
        }
    }

    Ok(())
}

fn strip_frontmatter(content: &str) -> &str {
    let trimmed = content.trim_start();
    if trimmed.starts_with("---") {
        if let Some(end) = trimmed[3..].find("---") {
            return &trimmed[3 + end + 3..];
        }
    }
    if trimmed.starts_with("+++") {
        if let Some(end) = trimmed[3..].find("+++") {
            return &trimmed[3 + end + 3..];
        }
    }
    content
}

async fn run_mdbook(project_dir: &Path) -> Result<BuildResult, String> {
    use tokio::process::Command;

    let mdbook_cmd = find_mdbook();

    let mut cmd = Command::new(&mdbook_cmd);
    cmd.arg("build")
        .current_dir(project_dir)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped());

    let child = cmd.spawn().map_err(|e| {
        format!(
            "Failed to run mdbook: {}. Install it with: cargo install mdbook",
            e
        )
    })?;

    let result = tokio::time::timeout(
        std::time::Duration::from_secs(120),
        child.wait_with_output(),
    )
    .await;

    match result {
        Ok(Ok(output)) => {
            let stdout_str = String::from_utf8_lossy(&output.stdout).to_string();
            let stderr_str = String::from_utf8_lossy(&output.stderr).to_string();
            let output_path = find_build_output(project_dir);
            if output.status.success() {
                ensure_directory_style_html_aliases(Path::new(&output_path))?;
            }

            Ok(BuildResult {
                success: output.status.success(),
                output_path,
                stdout: stdout_str,
                stderr: stderr_str,
            })
        }
        Ok(Err(e)) => Err(format!("mdbook process error: {}", e)),
        Err(_) => Err("mdbook build timed out after 120 seconds.".to_string()),
    }
}

fn find_build_output(project_dir: &Path) -> String {
    let toml_path = project_dir.join("book.toml");
    if let Ok(content) = std::fs::read_to_string(&toml_path) {
        let mut in_build = false;
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed == "[build]" {
                in_build = true;
                continue;
            }
            if in_build && trimmed.starts_with('[') {
                break; // End of [build] section
            }
            if in_build && trimmed.starts_with("build-dir") {
                let value = trimmed
                    .split('=')
                    .nth(1)
                    .unwrap_or("")
                    .trim()
                    .trim_matches('"')
                    .trim_matches('\'');
                if !value.is_empty() {
                    let build_dir = PathBuf::from(value);
                    if build_dir.is_absolute() {
                        return build_dir.to_string_lossy().to_string();
                    } else {
                        return project_dir
                            .join(build_dir)
                            .to_string_lossy()
                            .to_string();
                    }
                }
            }
        }
    }
    // Default
    project_dir.join("book").to_string_lossy().to_string()
}

fn find_mdbook() -> String {
    // 1. Check for bundled sidecar next to executable
    if let Ok(exe_path) = std::env::current_exe() {
        if let Some(exe_dir) = exe_path.parent() {
            let sidecar_name = if cfg!(windows) { "mdbook.exe" } else { "mdbook" };
            let sidecar_path = exe_dir.join(sidecar_name);
            if sidecar_path.exists() {
                return sidecar_path.to_string_lossy().to_string();
            }

            // Fallback for sidecars kept with target triple suffix
            if let Ok(entries) = std::fs::read_dir(exe_dir) {
                for entry in entries.flatten() {
                    let name = entry.file_name().to_string_lossy().to_string();
                    if name == "mdbook" || name == "mdbook.exe" || name.starts_with("mdbook-") {
                        let path = entry.path();
                        if path.is_file() {
                            return path.to_string_lossy().to_string();
                        }
                    }
                }
            }
        }
    }

    // 2. Try common system locations
    let candidates: Vec<&str> = if cfg!(windows) {
        vec!["mdbook.exe", "mdbook"]
    } else {
        vec!["mdbook", "/usr/local/bin/mdbook", "/usr/bin/mdbook"]
    };

    for candidate in &candidates {
        let path = Path::new(candidate);
        if path.exists() {
            return candidate.to_string();
        }
    }

    // 3. Check if mdbook is on PATH
    let which_cmd = if cfg!(windows) { "where" } else { "which" };
    if let Ok(output) = std::process::Command::new(which_cmd)
        .arg("mdbook")
        .output()
    {
        if output.status.success() {
            let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !path.is_empty() {
                return path.lines().next().unwrap_or(&path).to_string();
            }
        }
    }

    // 4. Fall back
    "mdbook".to_string()
}

fn ensure_summary_md(src_dir: &Path) -> Result<(), String> {
    // mdBook requires SUMMARY.md
    let summary = src_dir.join("SUMMARY.md");
    if summary.exists() {
        return Ok(());
    }

    let mut entries = Vec::new();

    for entry in WalkDir::new(src_dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
    {
        if !entry
            .path()
            .extension()
            .map_or(false, |ext| ext == "md" || ext == "markdown")
        {
            continue;
        }

        let relative = entry
            .path()
            .strip_prefix(src_dir)
            .unwrap_or(entry.path())
            .to_string_lossy()
            .replace('\\', "/");

        if relative == "SUMMARY.md" || relative == "index.md" {
            continue;
        }

        let name = entry
            .path()
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .replace('_', " ");

        entries.push((relative, name));
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut content = String::from("# Summary\n\n- [Home](./index.md)\n");
    for (relative, name) in entries {
        let summary_path = relative.replace(' ', "%20");
        content.push_str(&format!("- [{}](./{})\n", name, summary_path));
    }

    std::fs::write(&summary, content).map_err(|e| e.to_string())?;
    Ok(())
}

fn ensure_index_md(src_dir: &Path) -> Result<(), String> {
    let index = src_dir.join("index.md");
    if index.exists() {
        return Ok(());
    }

    // Check if there's a README.md we can rename
    let readme = src_dir.join("README.md");
    if readme.exists() {
        std::fs::rename(&readme, &index).map_err(|e| e.to_string())?;
        return Ok(());
    }

    // Create a minimal index.md
    std::fs::write(
        &index,
        "# Welcome\n\nWelcome to this knowledge base.\n",
    )
    .map_err(|e| e.to_string())?;
    Ok(())
}
