use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Debug, Serialize, Deserialize)]
pub struct BuildResult {
    pub success: bool,
    pub output_path: String,
    pub stdout: String,
    pub stderr: String,
}

/// Build the Zola site from markdown sources.
/// This creates a temporary Zola project, copies the theme and content, then runs Zola build.
#[tauri::command]
pub async fn build_site(
    app_handle: tauri::AppHandle,
    source_folder: String,
    output_folder: String,
    base_url: Option<String>,
) -> Result<BuildResult, String> {
    let source = PathBuf::from(&source_folder);
    let output = PathBuf::from(&output_folder);

    if !source.exists() {
        return Err("Source folder does not exist".to_string());
    }

    // Create a temporary Zola project directory
    let build_dir = std::env::temp_dir().join("frontdocs_build");
    if build_dir.exists() {
        std::fs::remove_dir_all(&build_dir).map_err(|e| e.to_string())?;
    }
    std::fs::create_dir_all(&build_dir).map_err(|e| e.to_string())?;

    // Write Zola config — use "/" so Zola generates root-relative paths,
    // then post-process to make them fully relative
    let _base = base_url; // reserved for future use
    let config = format!(
        r##"base_url = "/"
title = "Frontdocs Knowledge Base"
description = "Academic Knowledge Base generated by Frontdocs"
theme = "frontdocs"
compile_sass = true
build_search_index = true
generate_feeds = false

[[taxonomies]]
name = "tags"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
extra_syntaxes_and_themes = []
render_emoji = true

[extra]
accent_color = "#5C7CFA"
"##
    );
    std::fs::write(build_dir.join("config.toml"), config).map_err(|e| e.to_string())?;

    // Copy embedded theme
    setup_theme(&build_dir)?;

    // Copy and process content
    setup_content(&source, &build_dir)?;

    // Create output directory
    if !output.exists() {
        std::fs::create_dir_all(&output).map_err(|e| e.to_string())?;
    }

    // Run Zola build using sidecar or system install
    let zola_result = run_zola(&app_handle, &build_dir, &output).await?;

    // Post-process HTML to make all paths relative (strip leading "/")
    if zola_result.success {
        make_paths_relative(&output)?;
    }

    // Clean up build directory
    let _ = std::fs::remove_dir_all(&build_dir);

    Ok(zola_result)
}

#[tauri::command]
pub async fn preview_site(
    app_handle: tauri::AppHandle,
    source_folder: String,
) -> Result<BuildResult, String> {
    let temp_output = std::env::temp_dir().join("frontdocs_preview");
    build_site(
        app_handle,
        source_folder,
        temp_output.to_string_lossy().to_string(),
        Some("http://127.0.0.1:1111".to_string()),
    )
    .await
}

fn setup_theme(build_dir: &PathBuf) -> Result<(), String> {
    let theme_dir = build_dir.join("themes").join("frontdocs");
    let templates_dir = theme_dir.join("templates");
    let sass_dir = theme_dir.join("sass");
    let static_dir = theme_dir.join("static");
    let static_js = static_dir.join("js");
    let shortcodes_dir = templates_dir.join("shortcodes");

    for dir in [
        &theme_dir,
        &templates_dir,
        &sass_dir,
        &static_dir,
        &static_js,
        &shortcodes_dir,
    ] {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }

    // Write theme config
    std::fs::write(
        theme_dir.join("theme.toml"),
        r#"name = "frontdocs"
description = "Academic knowledge base theme for Frontdocs"
license = "MIT"
min_version = "0.19.0"
"#,
    )
    .map_err(|e| e.to_string())?;

    // Embed theme files
    std::fs::write(
        templates_dir.join("base.html"),
        include_str!("../../../zola-theme/templates/base.html"),
    )
    .map_err(|e| e.to_string())?;

    std::fs::write(
        templates_dir.join("index.html"),
        include_str!("../../../zola-theme/templates/index.html"),
    )
    .map_err(|e| e.to_string())?;

    std::fs::write(
        templates_dir.join("page.html"),
        include_str!("../../../zola-theme/templates/page.html"),
    )
    .map_err(|e| e.to_string())?;

    std::fs::write(
        templates_dir.join("section.html"),
        include_str!("../../../zola-theme/templates/section.html"),
    )
    .map_err(|e| e.to_string())?;

    std::fs::write(
        shortcodes_dir.join("cite.html"),
        include_str!("../../../zola-theme/templates/shortcodes/cite.html"),
    )
    .map_err(|e| e.to_string())?;

    std::fs::write(
        shortcodes_dir.join("note.html"),
        include_str!("../../../zola-theme/templates/shortcodes/note.html"),
    )
    .map_err(|e| e.to_string())?;

    std::fs::write(
        sass_dir.join("style.scss"),
        include_str!("../../../zola-theme/sass/style.scss"),
    )
    .map_err(|e| e.to_string())?;

    std::fs::write(
        static_js.join("main.js"),
        include_str!("../../../zola-theme/static/js/main.js"),
    )
    .map_err(|e| e.to_string())?;

    Ok(())
}

fn setup_content(source: &PathBuf, build_dir: &PathBuf) -> Result<(), String> {
    let content_dir = build_dir.join("content");
    std::fs::create_dir_all(&content_dir).map_err(|e| e.to_string())?;

    // Walk the source folder and copy markdown files preserving structure
    for entry in walkdir::WalkDir::new(source)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        let relative = entry.path().strip_prefix(source).unwrap_or(entry.path());

        if entry.file_type().is_dir() {
            let dest = content_dir.join(relative);
            std::fs::create_dir_all(&dest).map_err(|e| e.to_string())?;

            // Create _index.md for sections if it doesn't exist
            let index_file = dest.join("_index.md");
            if !index_file.exists() && relative.to_string_lossy() != "" {
                let section_name = relative
                    .file_name()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .to_string();
                let title = section_name
                    .replace('-', " ")
                    .replace('_', " ");
                // Capitalize first letter of each word
                let title: String = title
                    .split_whitespace()
                    .map(|w| {
                        let mut c = w.chars();
                        match c.next() {
                            None => String::new(),
                            Some(f) => f.to_uppercase().to_string() + c.as_str(),
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(" ");

                let content = format!(
                    r#"+++
title = "{title}"
sort_by = "title"
template = "section.html"
+++
"#
                );
                std::fs::write(&index_file, content).map_err(|e| e.to_string())?;
            }
        } else if entry
            .path()
            .extension()
            .map_or(false, |ext| ext == "md" || ext == "markdown")
        {
            let dest = content_dir.join(relative);
            let content = std::fs::read_to_string(entry.path()).map_err(|e| e.to_string())?;

            // Ensure frontmatter exists; add default if missing
            let processed = ensure_frontmatter(&content, entry.path());
            std::fs::write(&dest, processed).map_err(|e| e.to_string())?;
        } else if entry
            .path()
            .extension()
            .map_or(false, |ext| ext == "bib")
        {
            // Copy bibliography files to static
            let static_dir = build_dir.join("static");
            let dest = static_dir.join(entry.file_name());
            std::fs::copy(entry.path(), dest).map_err(|e| e.to_string())?;
        }
    }

    // Create root _index.md if it doesn't exist
    let root_index = content_dir.join("_index.md");
    if !root_index.exists() {
        std::fs::write(
            &root_index,
            r#"+++
title = "Knowledge Base"
sort_by = "title"
template = "index.html"
+++

Welcome to the Frontdocs Knowledge Base.
"#,
        )
        .map_err(|e| e.to_string())?;
    }

    Ok(())
}

fn ensure_frontmatter(content: &str, path: &std::path::Path) -> String {
    let trimmed = content.trim_start();
    if trimmed.starts_with("---") || trimmed.starts_with("+++") {
        // Already has frontmatter - convert YAML (---) to TOML (+++) for Zola
        if trimmed.starts_with("---") {
            return convert_yaml_to_toml_frontmatter(content, path);
        }
        return content.to_string();
    }

    // Generate default frontmatter
    let file_stem = path
        .file_stem()
        .unwrap_or_default()
        .to_string_lossy()
        .to_string();
    let title = file_stem.replace('-', " ").replace('_', " ");
    // Capitalize words
    let title: String = title
        .split_whitespace()
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + c.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ");

    format!(
        r#"+++
title = "{title}"
date = "{date}"
[taxonomies]
tags = []
+++

{content}"#,
        date = chrono_like_date(),
    )
}

fn convert_yaml_to_toml_frontmatter(content: &str, path: &std::path::Path) -> String {
    // Simple YAML to TOML frontmatter conversion for common fields
    let trimmed = content.trim_start();
    if let Some(end) = trimmed[3..].find("---") {
        let yaml_part = &trimmed[3..3 + end];
        let body = &trimmed[3 + end + 3..];
        
        let mut title = None;
        let mut date = None;
        let mut description = None;
        let mut tags = Vec::new();
        
        for line in yaml_part.lines() {
            let line = line.trim();
            if let Some(val) = line.strip_prefix("title:") {
                title = Some(val.trim().trim_matches('"').trim_matches('\'').to_string());
            } else if let Some(val) = line.strip_prefix("date:") {
                date = Some(val.trim().trim_matches('"').trim_matches('\'').to_string());
            } else if let Some(val) = line.strip_prefix("description:") {
                description = Some(val.trim().trim_matches('"').trim_matches('\'').to_string());
            } else if line.starts_with("- ") && !tags.is_empty() || line.starts_with("tags:") {
                if let Some(val) = line.strip_prefix("- ") {
                    tags.push(val.trim().trim_matches('"').trim_matches('\'').to_string());
                }
            }
        }

        let title = title.unwrap_or_else(|| {
            path.file_stem()
                .unwrap_or_default()
                .to_string_lossy()
                .replace('-', " ")
                .replace('_', " ")
        });
        let date = date.unwrap_or_else(chrono_like_date);

        let mut toml = format!("+++\ntitle = \"{title}\"\ndate = \"{date}\"\n");
        if let Some(desc) = description {
            toml.push_str(&format!("description = \"{desc}\"\n"));
        }
        if !tags.is_empty() {
            let tags_str: Vec<String> = tags.iter().map(|t| format!("\"{t}\"")).collect();
            toml.push_str(&format!("\n[taxonomies]\ntags = [{}]\n", tags_str.join(", ")));
        }
        toml.push_str("+++\n");
        toml.push_str(body);
        return toml;
    }
    content.to_string()
}

/// Post-process built HTML/CSS/JS files to convert root-relative paths ("/" prefix)
/// into proper relative paths so the site works when opened from any location.
fn make_paths_relative(output_dir: &PathBuf) -> Result<(), String> {
    for entry in walkdir::WalkDir::new(output_dir)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        let path = entry.path();
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if !matches!(ext, "html" | "css" | "js" | "xml") {
            continue;
        }
        let content = std::fs::read_to_string(path).map_err(|e| e.to_string())?;

        // Calculate the relative prefix from this file's depth
        // e.g. output_dir/algorithms/grover/index.html → depth 2 → "../../"
        let rel = path.parent().unwrap_or(path);
        let depth = rel
            .strip_prefix(output_dir)
            .unwrap_or(std::path::Path::new(""))
            .components()
            .count();
        let prefix = if depth == 0 {
            "./".to_string()
        } else {
            "../".repeat(depth)
        };

        // Replace href="/...", src="/...", action="/...", url(/...), content="/..."
        let re = regex::Regex::new(r#"((?:href|src|action|content)\s*=\s*")/((?:[^"]*)")"#)
            .map_err(|e| e.to_string())?;
        let replaced = re.replace_all(&content, |caps: &regex::Captures| {
            format!("{}{}{}", &caps[1], &prefix, &caps[2])
        });

        // Also handle url(/) patterns in CSS
        let re_css = regex::Regex::new(r#"url\(\s*['"]?/([^)'"]*?)['"]?\s*\)"#)
            .map_err(|e| e.to_string())?;
        let replaced = re_css.replace_all(&replaced, |caps: &regex::Captures| {
            format!("url({}{})", &prefix, &caps[1])
        });

        if replaced != content {
            std::fs::write(path, replaced.as_ref()).map_err(|e| e.to_string())?;
        }
    }
    Ok(())
}

fn chrono_like_date() -> String {
    // Return current date in YYYY-MM-DD format without chrono dependency
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    let secs = now.as_secs();
    let days = secs / 86400;
    // Approximate date calculation
    let years = 1970 + (days / 365);
    let remaining_days = days % 365;
    let month = remaining_days / 30 + 1;
    let day = remaining_days % 30 + 1;
    format!("{:04}-{:02}-{:02}", years, month.min(12), day.min(28))
}

async fn run_zola(
    app_handle: &tauri::AppHandle,
    build_dir: &PathBuf,
    output_dir: &PathBuf,
) -> Result<BuildResult, String> {
    use tokio::process::Command;

    // Try sidecar first, fall back to system Zola
    let zola_path = find_zola(app_handle);

    let mut child = Command::new(&zola_path)
        .args([
            "--root",
            &build_dir.to_string_lossy(),
            "build",
            "--output-dir",
            &output_dir.to_string_lossy(),
            "--force",
        ])
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| format!("Failed to run Zola: {}. Make sure Zola is installed or the sidecar binary is available.", e))?;

    // Wait with a 120-second timeout
    let result = tokio::time::timeout(
        std::time::Duration::from_secs(120),
        child.wait(),
    )
    .await;

    match result {
        Ok(Ok(status)) => {
            // Read captured output
            let mut stdout_str = String::new();
            let mut stderr_str = String::new();
            if let Some(mut out) = child.stdout.take() {
                use tokio::io::AsyncReadExt;
                let _ = out.read_to_string(&mut stdout_str).await;
            }
            if let Some(mut err) = child.stderr.take() {
                use tokio::io::AsyncReadExt;
                let _ = err.read_to_string(&mut stderr_str).await;
            }
            Ok(BuildResult {
                success: status.success(),
                output_path: output_dir.to_string_lossy().to_string(),
                stdout: stdout_str,
                stderr: stderr_str,
            })
        }
        Ok(Err(e)) => Err(format!("Zola process error: {}", e)),
        Err(_) => {
            // Timeout — kill the child process
            let _ = child.kill().await;
            Err("Zola build timed out after 120 seconds. Check that your Zola binary is valid (not a placeholder script).".to_string())
        }
    }
}

fn find_zola(app_handle: &tauri::AppHandle) -> String {
    // Try to find the sidecar binary bundled with the app
    let resource_dir = app_handle
        .path()
        .resource_dir()
        .ok();

    if let Some(dir) = resource_dir {
        let sidecar = dir.join("binaries").join("zola");
        if is_real_binary(&sidecar) {
            return sidecar.to_string_lossy().to_string();
        }
        let sidecar_exe = dir.join("binaries").join("zola.exe");
        if is_real_binary(&sidecar_exe) {
            return sidecar_exe.to_string_lossy().to_string();
        }
    }

    // Try sidecar in development (relative to project root)
    let dev_sidecar = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("binaries")
        .join(format!("zola-{}", std::env::consts::ARCH.replace("x86_64", "x86_64-unknown-linux-gnu")));
    if is_real_binary(&dev_sidecar) {
        return dev_sidecar.to_string_lossy().to_string();
    }

    // Fall back to system-installed Zola
    "zola".to_string()
}

/// Check that a path exists and is an actual ELF/Mach-O/PE binary, not a shell script placeholder.
fn is_real_binary(path: &std::path::Path) -> bool {
    if !path.exists() {
        return false;
    }
    // Read the first 4 bytes to check for ELF magic or PE signature
    if let Ok(bytes) = std::fs::read(path) {
        if bytes.len() >= 4 {
            // ELF: 0x7f 'E' 'L' 'F'
            if bytes[0] == 0x7f && bytes[1] == b'E' && bytes[2] == b'L' && bytes[3] == b'F' {
                return true;
            }
            // PE: 'M' 'Z'
            if bytes[0] == b'M' && bytes[1] == b'Z' {
                return true;
            }
            // Mach-O
            if (bytes[0] == 0xFE && bytes[1] == 0xED && bytes[2] == 0xFA)
                || (bytes[0] == 0xCF && bytes[1] == 0xFA && bytes[2] == 0xED) {
                return true;
            }
        }
    }
    false
}

use tauri::Manager;
